import type { Article } from './articles';
export const demoArticles: Article[] = [
  { id: 'entente-notes', type: 'journal', slug: 'entente-notes', title: 'Entente：從一次 Hackathon，開始思考 agent 之間的交接', summary: '把比賽背景、作品、團隊分工與賽後反思，放在同一篇紀錄裡。', date: '2026-09-07', topic: 'Competitions', status: 'published', stage: '已完成', featured: true, event: 'FUTUREMODE BUILDMODE Gen-AI Hackathon 2026', role: '待補上你的實際角色', link: 'https://github.com/allenchenhan99/entente', body: '# 為什麼想做這個題目\n這是版型示範文章，並非正式的比賽紀錄。你可以在後台改成自己的故事。\n\n## 比賽與作品\nEntente 探索如何讓 coding agents 的工作交接帶有明確的條件與可檢查的證據。這一節可以放入當時的問題、時間限制與 demo。\n\n## 我的角色\n記錄自己負責的模組、做過的決策，以及和團隊合作的方式。\n\n## 賽後反思\n- 哪個判斷值得保留？\n- 哪件事下次會用不同的方式做？\n- 哪些方向值得繼續研究？' },
  { id: 'weekly-36', type: 'journal', slug: 'weekly-36', title: 'Week 36 / 留下可追溯的開發過程', summary: '這週做了什麼、還卡在哪裡，以及下週真正想解決的一個問題。', date: '2026-09-06', topic: 'Weekly Notes', status: 'published', stage: '進行中', featured: false, event: '', role: '', link: '', body: '# 這週的筆記\n這是週記版型示範。正式內容由你填寫。\n\n## 本週完成\n- 一個值得留下的改動\n- 一個比預期困難的問題\n\n## 學到的事\n用一個具體例子，說明自己的想法如何改變。\n\n## 下週\n只留下一件最想推進的事。' },
  { id: 'weekly-35', type: 'journal', slug: 'weekly-35', title: 'Week 35 / 給學習留一點空白', summary: '閱讀、實驗，以及那些還沒有答案的問題。', date: '2026-08-30', topic: 'Weekly Notes', status: 'published', stage: '進行中', featured: false, event: '', role: '', link: '', body: '# 給學習留一點空白\n這是週記版型示範。可以把本週讀過的內容、做過的實驗，以及尚未釐清的問題放在這裡。\n\n## 留下的問題\n哪個問題值得再花一週理解？' },
  { id: 'agent-handoffs', type: 'research', slug: 'agent-handoffs', title: '當 agent 說「完成」，我們該驗證什麼？', summary: '從 Task Contract 到 evidence：整理多 agent 協作中的驗收、修復與可追溯性問題。', date: '2026-09-08', topic: 'Agent Systems', status: 'published', stage: '進行中', featured: true, event: '', role: '', link: 'https://github.com/allenchenhan99/entente', body: '# 當 agent 說「完成」\n這是研究頁的版型示範，不代表已完成的研究結論。\n\n## 研究問題\n如何區分 agent 的自我回報，與可以重複檢查的交付證據？\n\n## 方法\n這裡可以描述任務設定、驗收條件、baseline，以及失敗案例。\n\n## 實驗紀錄\n```typescript\nconst delivery = {\n  status: "submitted",\n  evidence: []\n};\n```\n\n## 限制與下一步\n在有實際實驗以前，先明確區分設計假設與已驗證結果。' },
  { id: 'factor-decay', type: 'research', slug: 'factor-decay', title: 'Factor alpha decay：訊號何時失去解釋力？', summary: '以因子 IC 的生命週期為起點，整理 regime、crowding 與樣本外驗證的研究脈絡。', date: '2026-07-20', topic: 'Quantitative Finance', status: 'published', stage: '已完成', featured: false, event: '', role: '', link: 'https://github.com/allenchenhan99/Factor-Alpha-Decay-Estimation', body: '# Factor alpha decay\n這是研究文章版型示範；實際方法、數據與限制請以原始專案報告為準。\n\n## 研究問題\n因子的預測能力如何隨時間變化？\n\n## 方法與比較\n可以在這裡補上資料範圍、切分方式、baseline 與交易成本假設。\n\n## 結果\n放入主要結果圖，並說明支持與不支持的假設。\n\n## 限制\n明確交代資料偏誤與不能推論的範圍。' },
  { id: 'representation-draft', type: 'research', slug: 'representation-draft', title: 'Representation learning：下一個實驗', summary: '先把問題寫清楚，再決定模型。', date: '2026-09-09', topic: 'Deep Learning', status: 'draft', stage: '進行中', featured: false, event: '', role: '', link: '', body: '# 問題草稿\n這篇示範草稿只出現在後台。\n\n## 想回答的問題\n\n## 可以比較的 baseline\n\n## 評估方式' },
];
